[manager]

[preview]
max_width = 600
max_height = 900

[plugin]
previewers = [
	{ url = "*/", run = "folder" },
	{ mime = "text/*", run = "code" },
	{ mime = "image/*", run = "image" },
	{ mime = "video/*", run = "video" },
	{ mime = "application/pdf", run = "pdf" },
]
